server:
  port: 8083

logging:
  config:
    classpath: logback.xml

spring:
  application:
    name: survey-service
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://210.109.62.155:3306/survey_db
    username: dev1
    password: dev1test
  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: false
    show-sql: false
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: survey_platform
      auto-offset-reset: earliest
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: localhost:9092
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  output:
    ansi:
      enabled: always
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:5010/realms/team_cloud/protocol/openid-connect/certs

keycloak:
  realm: team_cloud
  bearer-only: true
  ssl-required: external
  resource: team_cloud_client
  auth-server-url: http://localhost:5010/
  credentials:
    secret: AvgjtsAvqQUNfo9DemEpANjMt3YrAtbt
#  public-client: false
#  principal-attribute: preferred_username

eureka:
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
